// @ts-nocheck
/**
 * PDF Export Utility
 * 
 * Exports property comparison to PDF using jsPDF
 * Note: Requires 'jspdf' to be installed: npm install jspdf
 * TypeScript checking is disabled until jsPDF is installed
 */

import type { ComparisonProperty } from '../stores/comparisonStore';

export const exportComparisonToPDF = async (properties: ComparisonProperty[]) => {
    try {
        // Dynamically import jsPDF only when needed
        const { jsPDF } = await import('jspdf');
        const doc = new jsPDF();

        // Header
        doc.setFontSize(20);
        doc.text('Property Comparison Report', 20, 20);

        doc.setFontSize(10);
        doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 30);
        doc.text(`Comparing ${properties.length} properties`, 20, 36);

        // Table starting position
        let yPos = 50;
        const lineHeight = 10;
        const pageHeight = doc.internal.pageSize.height;
        const marginBottom = 20;

        // Function to check if we need a new page
        const checkPageBreak = () => {
            if (yPos > pageHeight - marginBottom) {
                doc.addPage();
                yPos = 20;
            }
        };

        // For each property
        properties.forEach((property, idx) => {
            checkPageBreak();

            // Property header
            doc.setFontSize(14);
            doc.setFont(undefined, 'bold');
            doc.text(`Property ${idx + 1}: ${property.address}`, 20, yPos);
            yPos += lineHeight;

            doc.setFontSize(10);
            doc.setFont(undefined, 'normal');

            // Property details
            const details = [
                `Price: $${property.price.toLocaleString()}`,
                property.bedrooms ? `Bedrooms: ${property.bedrooms}` : null,
                property.bathrooms ? `Bathrooms: ${property.bathrooms}` : null,
                property.sqft ? `Square Feet: ${property.sqft.toLocaleString()}` : null,
                property.yearBuilt ? `Year Built: ${property.yearBuilt}` : null,
                property.monthlyRent ? `Monthly Rent: $${property.monthlyRent.toLocaleString()}` : null,
                property.cashFlow ? `Cash Flow: ${property.cashFlow >= 0 ? '+' : ''}$${property.cashFlow.toLocaleString()}` : null,
                property.cocReturn ? `CoC Return: ${property.cocReturn.toFixed(2)}%` : null,
                property.capRate ? `Cap Rate: ${property.capRate.toFixed(2)}%` : null,
            ].filter(Boolean);

            details.forEach(detail => {
                checkPageBreak();
                if (detail) {
                    doc.text(detail, 25, yPos);
                    yPos += 6;
                }
            });

            yPos += 5; // Space between properties
        });

        // Summary section
        checkPageBreak();
        yPos += 10;
        doc.setFontSize(14);
        doc.setFont(undefined, 'bold');
        doc.text('Comparison Summary', 20, yPos);
        yPos += lineHeight;

        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');

        // Find best values
        const prices = properties.map(p => p.price).filter(p => p > 0);
        const cashFlows = properties.map(p => p.cashFlow).filter(c => c !== undefined) as number[];

        if (prices.length > 0) {
            checkPageBreak();
            doc.text(`Lowest Price: $${Math.min(...prices).toLocaleString()}`, 20, yPos);
            yPos += 6;
            doc.text(`Highest Price: $${Math.max(...prices).toLocaleString()}`, 20, yPos);
            yPos += 6;
        }

        if (cashFlows.length > 0) {
            checkPageBreak();
            doc.text(`Best Cash Flow: $${Math.max(...cashFlows).toLocaleString()}/mo`, 20, yPos);
            yPos += 6;
        }

        // Footer
        const footerY = pageHeight - 15;
        doc.setFontSize(8);
        doc.setTextColor(128);
        doc.text('Generated by Civitas AI - Real Estate Intelligence Platform', 20, footerY);

        // Save the PDF
        doc.save(`property-comparison-${Date.now()}.pdf`);
    } catch (error) {
        console.error('PDF Export Error:', error);
        alert('PDF export requires jsPDF package.\n\nPlease install it:\nnpm install jspdf\n\nThen try exporting again.');
    }
};
