/**
 * Terms of Service Page
 * Terms and conditions for using Vasthu
 */

import React from 'react';
import { ArrowLeft, FileText, AlertTriangle, CreditCard, UserX, RefreshCw } from 'lucide-react';
import { designTokens } from '../styles/design-tokens';

interface TermsPageProps {
  onBack?: () => void;
}

export const TermsPage: React.FC<TermsPageProps> = ({ onBack }) => {
  const sections = [
    {
      icon: <FileText size={20} />,
      title: 'Acceptance of Terms',
      content: `By accessing and using Vasthu ("the Service"), you accept and agree to be bound by the terms and conditions of this agreement. If you do not agree to these terms, please do not use our Service.
      
These Terms of Service may be updated from time to time. We will notify you of any material changes, and your continued use of the Service constitutes acceptance of the updated terms.`,
    },
    {
      icon: <UserX size={20} />,
      title: 'User Accounts',
      content: `To use certain features of the Service, you must register for an account. You agree to:
      
• Provide accurate, current, and complete information
• Maintain the security of your password
• Accept responsibility for all activities under your account
• Notify us immediately of any unauthorized use
      
We reserve the right to suspend or terminate accounts that violate these terms or engage in fraudulent activity.`,
    },
    {
      icon: <CreditCard size={20} />,
      title: 'Subscription and Billing',
      content: `Vasthu offers various subscription plans with different features and pricing:
      
• Subscriptions automatically renew unless cancelled
• You can cancel at any time from your account settings
• Refunds are issued on a case-by-case basis
• Price changes will be communicated 30 days in advance
• Failed payments may result in service suspension
      
All fees are exclusive of applicable taxes, which will be added to your invoice.`,
    },
    {
      icon: <AlertTriangle size={20} />,
      title: 'Acceptable Use',
      content: `You agree NOT to:
      
• Use the Service for any illegal purpose
• Attempt to gain unauthorized access to our systems
• Interfere with the Service or disrupt servers/networks
• Scrape, copy, or redistribute our data without permission
• Reverse engineer or decompile any part of the Service
• Use the Service to harm, harass, or defame others
• Impersonate any person or entity
      
Violation of these terms may result in immediate termination of your account.`,
    },
    {
      icon: <FileText size={20} />,
      title: 'Intellectual Property',
      content: `All content, features, and functionality of the Service are owned by Vasthu and protected by copyright, trademark, and other intellectual property laws.
      
• You retain ownership of data you input into the Service
• We grant you a limited license to use the Service
• You may not copy, modify, or distribute our proprietary content
• Our trademarks and logos may not be used without permission
      
Reports and analyses generated by the Service are for your personal or business use only.`,
    },
    {
      icon: <RefreshCw size={20} />,
      title: 'Data Accuracy and Disclaimers',
      content: `While we strive for accuracy, we cannot guarantee that:
      
• Property data is always current or error-free
• Market analyses reflect real-time conditions
• Investment recommendations will be profitable
      
THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. We are not responsible for investment decisions made based on our analyses. You should conduct your own due diligence and consult with professionals.`,
    },
    {
      icon: <AlertTriangle size={20} />,
      title: 'Limitation of Liability',
      content: `To the fullest extent permitted by law, Vasthu shall not be liable for:
      
• Any indirect, incidental, or consequential damages
• Loss of profits, revenue, or data
• Service interruptions or technical issues
• Actions taken based on information provided
      
Our total liability is limited to the amount you paid us in the past 12 months.`,
    },
  ];

  return (
    <div style={{
      minHeight: '100vh',
      backgroundColor: designTokens.colors.chat.bg,
      padding: `${designTokens.spacing.xl} ${designTokens.spacing.lg}`,
    }}>
      {/* Header */}
      <div style={{
        maxWidth: '900px',
        margin: '0 auto',
        marginBottom: designTokens.spacing.xl,
      }}>
        {/* Back Button */}
        {onBack && (
          <button
            onClick={onBack}
            style={{
              display: 'flex',
              alignItems: 'center',
              gap: designTokens.spacing.xs,
              padding: `${designTokens.spacing.sm} ${designTokens.spacing.md}`,
              backgroundColor: 'transparent',
              color: designTokens.colors.text.secondary,
              border: 'none',
              borderRadius: designTokens.radius.md,
              fontSize: '14px',
              fontWeight: designTokens.typography.fontWeight.medium,
              cursor: 'pointer',
              marginBottom: designTokens.spacing.md,
              transition: `all ${designTokens.transition.fast}`,
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.color = designTokens.colors.brand.primary;
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.color = designTokens.colors.text.secondary;
            }}
          >
            <ArrowLeft size={18} />
            Back
          </button>
        )}
        <h1 style={{
          fontSize: '32px',
          fontWeight: designTokens.typography.fontWeight.semibold,
          color: designTokens.colors.text.primary,
          marginBottom: designTokens.spacing.sm,
        }}>
          Terms of Service
        </h1>
        <p style={{
          fontSize: '15px',
          color: designTokens.colors.text.tertiary,
          margin: 0,
        }}>
          Last updated: January 17, 2026
        </p>
      </div>

      {/* Content */}
      <div style={{
        maxWidth: '900px',
        margin: '0 auto',
        display: 'flex',
        flexDirection: 'column',
        gap: designTokens.spacing.lg,
      }}>
        {/* Introduction */}
        <div style={{
          backgroundColor: designTokens.colors.chat.surface,
          borderRadius: designTokens.radius.md,
          padding: designTokens.spacing.lg,
          border: `1px solid ${designTokens.colors.sidebar.border}`,
        }}>
          <p style={{
            fontSize: '15px',
            color: designTokens.colors.text.secondary,
            lineHeight: 1.7,
            margin: 0,
          }}>
            Welcome to Vasthu. These Terms of Service govern your use of our platform and services. By using Vasthu, you agree to comply with these terms. Please read them carefully.
          </p>
        </div>

        {/* Sections */}
        {sections.map((section, index) => (
          <div
            key={index}
            style={{
              backgroundColor: designTokens.colors.chat.surface,
              borderRadius: designTokens.radius.md,
              padding: designTokens.spacing.lg,
              border: `1px solid ${designTokens.colors.sidebar.border}`,
            }}
          >
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: designTokens.spacing.sm,
              marginBottom: designTokens.spacing.md,
            }}>
              <div style={{
                width: '40px',
                height: '40px',
                borderRadius: designTokens.radius.md,
                backgroundColor: designTokens.colors.brand.subtle,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: designTokens.colors.brand.light,
                flexShrink: 0,
              }}>
                {section.icon}
              </div>
              <h2 style={{
                fontSize: '20px',
                fontWeight: designTokens.typography.fontWeight.semibold,
                color: designTokens.colors.text.primary,
                margin: 0,
              }}>
                {section.title}
              </h2>
            </div>
            <div style={{
              fontSize: '14px',
              color: designTokens.colors.text.secondary,
              lineHeight: 1.7,
              whiteSpace: 'pre-line',
            }}>
              {section.content}
            </div>
          </div>
        ))}

        {/* Contact */}
        <div style={{
          backgroundColor: designTokens.colors.chat.surface,
          borderRadius: designTokens.radius.md,
          padding: designTokens.spacing.lg,
          border: `1px solid ${designTokens.colors.sidebar.border}`,
        }}>
          <h3 style={{
            fontSize: '18px',
            fontWeight: designTokens.typography.fontWeight.semibold,
            color: designTokens.colors.text.primary,
            marginBottom: designTokens.spacing.sm,
          }}>
            Questions About These Terms?
          </h3>
          <p style={{
            fontSize: '14px',
            color: designTokens.colors.text.secondary,
            lineHeight: 1.7,
            margin: 0,
          }}>
            If you have any questions about these Terms of Service, please contact us at{' '}
            <a
              href="mailto:legal@vasthu.ai"
              style={{
                color: designTokens.colors.brand.light,
                textDecoration: 'none',
                fontWeight: designTokens.typography.fontWeight.medium,
              }}
            >
              legal@vasthu.ai
            </a>
            {' '}or through our contact page.
          </p>
        </div>
      </div>
    </div>
  );
};
